// ==============================================================================
// AI Launcher Pro - Config IO (T4: registry-driven)
// Export/import of the full app config as JSON.
//
// The payload is generated by walking the central REGISTRY (lib/storage/registry.ts)
// instead of a hardcoded list. This guarantees a backup includes EVERY known key —
// profiles (v15), workspaces, runbooks, budget, custom CLIs/IDEs, overrides,
// cli-order, theme/accent/font/locale/density, directory memory, etc. — and not
// just providers/presets/config as the legacy v15 implementation did.
//
// Secrets are redacted on export:
//   - provider profile `apiKey`
//   - provider profile `extraEnv` keys matching /token|key|secret|bearer|password/i
// Secret-prefixed localStorage keys are not in the registry, so they never leak.
//
// Backward compatibility: importConfig still reads OLD backups whose top level was
// { version, exportedAt, providers, presets, config, settings } — those fields are
// mapped onto the corresponding registry ids. New backups use a `keys` map keyed
// by registry id; both shapes are accepted.
// ==============================================================================

import { z } from 'zod';
import {
  backupEntries,
  REGISTRY,
  readRawForBackup,
  type RegistryEntry,
  type RegistryId,
} from './storage';

const REDACTED = '{{REDACTED}}';

function isSecretField(key: string): boolean {
  return /api[_-]?key|access[_-]?token|refresh[_-]?token|auth[_-]?token|secret|bearer|password|credential|authorization/i.test(
    key,
  );
}

// Tolerant schema: the `keys` map holds arbitrary per-key blobs (each validated
// later by its own registry schema on read). Legacy top-level fields stay optional
// for backward-compatible import.
const ConfigDumpSchema = z.object({
  version: z.string().min(1),
  exportedAt: z.string().min(1),
  manifest: z
    .object({
      format: z.string().optional(),
      schemaVersion: z.number().optional(),
      appVersion: z.string().optional(),
      exportedAt: z.string().optional(),
      keyCount: z.number().optional(),
      keys: z.array(z.string()).optional(),
      redactedCount: z.number().optional(),
    })
    .passthrough()
    .optional(),
  // New registry-driven payload.
  keys: z.record(z.string(), z.unknown()).optional(),
  // Legacy fields (pre-T4 backups).
  providers: z.record(z.string(), z.unknown()).optional(),
  presets: z.unknown().optional(),
  config: z.record(z.string(), z.unknown()).optional(),
  settings: z.record(z.string(), z.unknown()).optional(),
});

type ConfigDump = z.infer<typeof ConfigDumpSchema>;

export interface ConfigImportPreview {
  ok: true;
  version: string;
  exportedAt: string;
  keyCount: number;
  knownKeys: string[];
  unknownKeys: string[];
  redactedCount: number;
  manifest?: ConfigDump['manifest'];
}

// --- Secret redaction (providers state) --------------------------------------

function redactEnv(env: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(env)) {
    out[k] = isSecretField(k) ? REDACTED : v;
  }
  return out;
}

function redactProviderProfile(p: Record<string, unknown>): Record<string, unknown> {
  const redacted: Record<string, unknown> = { ...p };
  if (typeof redacted.apiKey === 'string' && redacted.apiKey.length > 0) {
    redacted.apiKey = REDACTED;
  }
  if (redacted.extraEnv && typeof redacted.extraEnv === 'object') {
    redacted.extraEnv = redactEnv(redacted.extraEnv as Record<string, unknown>);
  }
  return redacted;
}

function redactProvidersState(state: unknown): unknown {
  if (!state || typeof state !== 'object') return state;
  const next: Record<string, unknown> = { ...(state as Record<string, unknown>) };
  if (Array.isArray(next.profiles)) {
    next.profiles = (next.profiles as Array<Record<string, unknown>>).map(redactProviderProfile);
  }
  return next;
}

function redactSecretsDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(redactSecretsDeep);
  if (!value || typeof value !== 'object') return value;
  const out: Record<string, unknown> = {};
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    out[key] = isSecretField(key) ? REDACTED : redactSecretsDeep(child);
  }
  return out;
}

function countRedactedDeep(value: unknown): number {
  if (Array.isArray(value)) {
    return value.reduce<number>((sum, child) => sum + countRedactedDeep(child), 0);
  }
  if (!value || typeof value !== 'object') return value === REDACTED ? 1 : 0;
  return Object.values(value as Record<string, unknown>).reduce<number>(
    (sum, child) => sum + countRedactedDeep(child),
    0,
  );
}

/** Redact a single backup value just before it leaves the machine. */
function redactForBackup(id: RegistryId, value: unknown): unknown {
  const prepared = id === 'providers' ? redactProvidersState(value) : value;
  return redactSecretsDeep(prepared);
}

// --- Export ------------------------------------------------------------------

export function exportConfig(appVersion: string): string {
  const keys: Record<string, unknown> = {};
  for (const e of backupEntries()) {
    const raw = readRawForBackup(e);
    if (raw === undefined) continue; // skip absent keys — keep the backup lean
    keys[e.id] = redactForBackup(e.id as RegistryId, raw);
  }
  const exportedAt = new Date().toISOString();
  const keyIds = Object.keys(keys).sort();
  const redactedCount = countRedactedDeep(keys);

  const dump: ConfigDump = {
    version: appVersion,
    exportedAt,
    manifest: {
      format: 'ai-launcher-config',
      schemaVersion: 2,
      appVersion,
      exportedAt,
      keyCount: keyIds.length,
      keys: keyIds,
      redactedCount,
    },
    keys,
  };
  return JSON.stringify(dump, null, 2);
}

// --- Import ------------------------------------------------------------------

export type ImportResult =
  | { ok: true; redactedCount: number }
  | { ok: false; error: string };

function parseDump(raw: string): { ok: true; dump: ConfigDump } | { ok: false; error: string } {
  let parsedJson: unknown;
  try {
    parsedJson = JSON.parse(raw);
  } catch {
    return { ok: false, error: 'Arquivo nao e JSON valido.' };
  }

  const result = ConfigDumpSchema.safeParse(parsedJson);
  if (!result.success) {
    const first = result.error.issues[0];
    const path = first.path.join('.');
    return {
      ok: false,
      error: `Formato de config invalido${path ? ` em "${path}"` : ''}: ${first.message}`,
    };
  }
  return { ok: true, dump: result.data };
}

/**
 * Normalize any accepted dump shape into a flat `{ registryId -> value }` map.
 * New backups carry a `keys` map directly; legacy backups expose providers/
 * presets/config/settings at the top level — map those onto registry ids.
 */
function dumpToKeyMap(dump: ConfigDump): Record<string, unknown> {
  const map: Record<string, unknown> = { ...(dump.keys ?? {}) };

  // Legacy top-level fields take effect only when not already provided by `keys`.
  if (dump.providers !== undefined && map.providers === undefined) {
    map.providers = dump.providers;
  }
  if (dump.presets !== undefined && map.presets === undefined) {
    map.presets = dump.presets;
  }
  if (dump.config !== undefined && map.config === undefined) {
    map.config = dump.config;
  }
  // Legacy `settings.displayFont` -> displayFont registry id.
  const settings = dump.settings;
  if (settings && typeof settings.displayFont === 'string' && map.displayFont === undefined) {
    map.displayFont = settings.displayFont;
  }

  return map;
}

/** Persist one registry value, honoring the entry's serialization mode. */
function persistEntry(entry: RegistryEntry, value: unknown): void {
  try {
    const serialized = entry.serialize === 'raw' ? String(value) : JSON.stringify(value);
    localStorage.setItem(entry.key, serialized);
  } catch {
    // ignore individual key write failures — best-effort restore
  }
}

/** Read the current stored value for an entry (parsed for json, raw for raw). */
function readCurrent(entry: RegistryEntry): unknown {
  return readRawForBackup(entry);
}

/**
 * Merge an incoming providers state into the existing one, preserving the local
 * apiKey when the incoming profile carries the REDACTED placeholder.
 */
function mergeProviders(existing: unknown, incoming: unknown): unknown {
  const exObj = existing && typeof existing === 'object' ? (existing as Record<string, unknown>) : {};
  const inObj = incoming && typeof incoming === 'object' ? (incoming as Record<string, unknown>) : {};
  const existingProfiles = Array.isArray(exObj.profiles)
    ? (exObj.profiles as Array<Record<string, unknown>>)
    : [];
  const incomingProfiles = Array.isArray(inObj.profiles)
    ? (inObj.profiles as Array<Record<string, unknown>>)
    : [];

  const byId = new Map<string, Record<string, unknown>>();
  for (const p of existingProfiles) {
    const id = typeof p.id === 'string' ? p.id : '';
    if (id) byId.set(id, p);
  }
  for (const p of incomingProfiles) {
    const id = typeof p.id === 'string' ? p.id : '';
    if (!id) continue;
    const prev = byId.get(id) ?? {};
    const merged: Record<string, unknown> = { ...prev, ...p };
    if (p.apiKey === REDACTED && typeof prev.apiKey === 'string') {
      merged.apiKey = prev.apiKey; // keep the local secret, drop the placeholder
    }
    byId.set(id, merged);
  }

  return { ...exObj, ...inObj, profiles: Array.from(byId.values()) };
}

/** Shallow-merge two records; arrays are concatenated, objects spread. */
function mergeValue(id: RegistryId, existing: unknown, incoming: unknown): unknown {
  if (id === 'providers') return mergeProviders(existing, incoming);
  if (Array.isArray(incoming)) {
    const base = Array.isArray(existing) ? existing : [];
    return [...base, ...incoming];
  }
  if (incoming && typeof incoming === 'object') {
    const base = existing && typeof existing === 'object' ? existing : {};
    return { ...(base as Record<string, unknown>), ...(incoming as Record<string, unknown>) };
  }
  // Scalars (raw strings, etc.): incoming wins.
  return incoming;
}

export function importConfig(raw: string, mode: 'merge' | 'replace'): ImportResult {
  const parsed = parseDump(raw);
  if (!parsed.ok) return parsed;
  const dump = parsed.dump;
  const keyMap = dumpToKeyMap(dump);
  const redactedCount = countRedactedDeep(keyMap);

  for (const [id, incoming] of Object.entries(keyMap)) {
    if (incoming === undefined) continue;
    // Only restore keys we know about (ignore unknown/foreign ids gracefully).
    const entry = (REGISTRY as Record<string, RegistryEntry | undefined>)[id];
    if (!entry) continue;

    if (mode === 'replace') {
      persistEntry(entry, incoming);
    } else {
      const existing = readCurrent(entry);
      const next = existing === undefined ? incoming : mergeValue(id as RegistryId, existing, incoming);
      persistEntry(entry, next);
    }
  }

  return { ok: true, redactedCount };
}

export function previewImportConfig(
  raw: string,
): ConfigImportPreview | { ok: false; error: string } {
  const parsed = parseDump(raw);
  if (!parsed.ok) return parsed;
  const dump = parsed.dump;
  const keyMap = dumpToKeyMap(dump);
  const keys = Object.keys(keyMap).sort();
  const knownKeys = keys.filter((id) => Boolean((REGISTRY as Record<string, unknown>)[id]));
  const unknownKeys = keys.filter((id) => !knownKeys.includes(id));
  return {
    ok: true,
    version: dump.version,
    exportedAt: dump.exportedAt,
    keyCount: keys.length,
    knownKeys,
    unknownKeys,
    redactedCount: countRedactedDeep(keyMap),
    manifest: dump.manifest,
  };
}

export function downloadConfigJson(appVersion: string): void {
  const json = exportConfig(appVersion);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `ai-launcher-config-${new Date().toISOString().slice(0, 10)}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
