// ==============================================================================
// AI Launcher Pro - Storage Registry (central key catalog)
// Every persisted localStorage key the app knows about, each with:
//   - id        : stable identifier (key of STORAGE_KEYS)
//   - key       : the real localStorage key string
//   - schema    : zod schema used to validate on load (boundary validation)
//   - default   : value returned when the key is absent OR corrupted
//   - serialize : 'json' (default) or 'raw' for plain-string values
//   - secret    : true for entries that must NOT be exported in backups
//   - version   : schema/migration version (bump + add a migrate() when shape changes)
//
// The registry is the SINGLE source of truth for config export/import: backups
// are generated by walking REGISTRY, not a hardcoded list. This guarantees that
// every known key is included in a backup (the v15 bug: configIO only dumped
// providers/presets/config/font and silently dropped profiles, workspaces,
// runbooks, budget, custom CLIs/IDEs, overrides, cli-order and theme).
//
// Schemas are intentionally TOLERANT (.passthrough / .catchall(unknown)) — the
// goal here is boundary validation (corrupt blob -> default, never crash), not
// strict shape enforcement. Stricter validation lives in each domain module.
// ==============================================================================

import { z } from 'zod';
import { STORAGE_KEYS, type StorageKeyId } from './keys';

// --- Reusable leaf schemas ---------------------------------------------------

const launchProfileSchema = z
  .object({
    id: z.string(),
    name: z.string(),
    cliKeys: z.array(z.string()).default([]),
    toolKeys: z.array(z.string()).default([]),
    tags: z.array(z.string()).default([]),
    pinned: z.boolean().default(false),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .passthrough();

const workspaceProfileSchema = z
  .object({
    id: z.string(),
    name: z.string(),
    directory: z.string().default(''),
    cliKeys: z.array(z.string()).default([]),
    envVars: z.record(z.string(), z.string()).default({}),
    tags: z.array(z.string()).default([]),
    pinned: z.boolean().default(false),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .passthrough();

const runbookSchema = z
  .object({
    id: z.string(),
    name: z.string(),
    steps: z.array(z.unknown()).default([]),
    tags: z.array(z.string()).default([]),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .passthrough();

const budgetLimitSchema = z
  .object({
    providerKey: z.string(),
    limitUsd: z.number(),
    periodDays: z.number(),
    alertAtPercent: z.number(),
    periodAnchor: z.string().optional(),
  })
  .passthrough();

const customCliSchema = z
  .object({
    key: z.string(),
    name: z.string(),
    installCmd: z.string(),
    versionCmd: z.string(),
    createdAt: z.number(),
  })
  .passthrough();

const customIdeSchema = z
  .object({
    key: z.string(),
    name: z.string(),
    detectCmd: z.string(),
    launchCmd: z.string(),
    createdAt: z.number(),
  })
  .passthrough();

const cliOverrideSchema = z
  .object({
    name: z.string().optional(),
    iconEmoji: z.string().optional(),
    iconDataUrl: z.string().optional(),
  })
  .passthrough();

const overridesSchema = z.record(z.string(), cliOverrideSchema);

const inboxEventSchema = z
  .object({
    id: z.string().min(1),
    type: z.enum(['session', 'budget', 'update', 'doctor']),
    titleKey: z.string().min(1),
    titleParams: z.record(z.string(), z.union([z.string(), z.number()])).optional(),
    bodyKey: z.string().optional(),
    bodyParams: z.record(z.string(), z.union([z.string(), z.number()])).optional(),
    ts: z.number(),
    read: z.boolean(),
    targetTab: z.string(),
  })
  .passthrough();

const inboxStateSchema = z
  .object({
    events: z.array(inboxEventSchema).default([]),
    doctorFailing: z.array(z.string()).default([]),
  })
  .passthrough();

// --- Registry entry type -----------------------------------------------------

export interface RegistryEntry<T = unknown> {
  id: StorageKeyId;
  key: string;
  /** Schema used to validate the deserialized value on load. */
  schema: z.ZodType<T>;
  /** Value returned on absence or corruption (must satisfy schema). */
  default: T;
  /** 'json' (default) round-trips through JSON; 'raw' stores the string verbatim. */
  serialize?: 'json' | 'raw';
  /** Secret entries are skipped during backup export. */
  secret?: boolean;
  /** Schema/migration version. Bump when the persisted shape changes. */
  version: number;
  /**
   * Optional migration: receives parsed-but-unknown data plus the version it was
   * stored under, returns data ready for `schema.safeParse`. Used on import of
   * older backups. Identity by default.
   */
  migrate?: (data: unknown, fromVersion: number) => unknown;
}

// Helper to build an entry while keeping `default` typed to the schema output.
function entry<S extends z.ZodType>(
  e: Omit<RegistryEntry<z.infer<S>>, 'schema'> & { schema: S },
): RegistryEntry<z.infer<S>> {
  // `version` is required on every entry below, so only `serialize` needs a
  // default here. (Spreading a `version` default would be overwritten anyway.)
  return { serialize: 'json', ...e } as RegistryEntry<z.infer<S>>;
}

// --- The registry ------------------------------------------------------------

export const REGISTRY = {
  config: entry({
    id: 'config',
    key: STORAGE_KEYS.config,
    schema: z.record(z.string(), z.unknown()),
    default: {} as Record<string, unknown>,
    version: 1,
  }),

  providers: entry({
    id: 'providers',
    key: STORAGE_KEYS.providers,
    // Validated loosely here; providers/storage.ts owns the strict shape + secrets.
    schema: z
      .object({ profiles: z.array(z.unknown()).optional(), activeId: z.string().optional() })
      .passthrough(),
    default: {} as Record<string, unknown>,
    version: 1,
  }),

  presets: entry({
    id: 'presets',
    key: STORAGE_KEYS.presets,
    schema: z.array(z.unknown()),
    default: [] as unknown[],
    version: 1,
  }),

  profiles: entry({
    id: 'profiles',
    key: STORAGE_KEYS.profiles,
    schema: z.array(launchProfileSchema),
    default: [] as z.infer<typeof launchProfileSchema>[],
    version: 1,
  }),

  workspaces: entry({
    id: 'workspaces',
    key: STORAGE_KEYS.workspaces,
    schema: z.array(workspaceProfileSchema),
    default: [] as z.infer<typeof workspaceProfileSchema>[],
    version: 1,
  }),

  // Active workspace id — stored as a raw string by workspaceStore.ts.
  activeWorkspace: entry({
    id: 'activeWorkspace',
    key: STORAGE_KEYS.activeWorkspace,
    schema: z.string(),
    default: '',
    serialize: 'raw',
    version: 1,
  }),

  runbooks: entry({
    id: 'runbooks',
    key: STORAGE_KEYS.runbooks,
    schema: z.object({ runbooks: z.array(runbookSchema).default([]) }).passthrough(),
    default: { runbooks: [] as z.infer<typeof runbookSchema>[] },
    version: 1,
  }),

  budget: entry({
    id: 'budget',
    key: STORAGE_KEYS.budget,
    schema: z.object({ limits: z.array(budgetLimitSchema).default([]) }).passthrough(),
    default: { limits: [] as z.infer<typeof budgetLimitSchema>[] },
    version: 1,
  }),

  inbox: entry({
    id: 'inbox',
    key: STORAGE_KEYS.inbox,
    schema: inboxStateSchema,
    default: { events: [], doctorFailing: [] } as z.infer<typeof inboxStateSchema>,
    version: 1,
  }),

  customClis: entry({
    id: 'customClis',
    key: STORAGE_KEYS.customClis,
    schema: z.array(customCliSchema),
    default: [] as z.infer<typeof customCliSchema>[],
    version: 1,
  }),

  customIdes: entry({
    id: 'customIdes',
    key: STORAGE_KEYS.customIdes,
    schema: z.array(customIdeSchema),
    default: [] as z.infer<typeof customIdeSchema>[],
    version: 1,
  }),

  cliOverrides: entry({
    id: 'cliOverrides',
    key: STORAGE_KEYS.cliOverrides,
    schema: overridesSchema,
    default: {} as z.infer<typeof overridesSchema>,
    version: 1,
  }),

  ideOverrides: entry({
    id: 'ideOverrides',
    key: STORAGE_KEYS.ideOverrides,
    schema: overridesSchema,
    default: {} as z.infer<typeof overridesSchema>,
    version: 1,
  }),

  cliOrder: entry({
    id: 'cliOrder',
    key: STORAGE_KEYS.cliOrder,
    schema: z.array(z.string()),
    default: [] as string[],
    version: 1,
  }),

  // --- Appearance / preferences (raw string values) ---
  theme: entry({
    id: 'theme',
    key: STORAGE_KEYS.theme,
    schema: z.string(),
    default: '',
    serialize: 'raw',
    version: 1,
  }),

  accent: entry({
    id: 'accent',
    key: STORAGE_KEYS.accent,
    schema: z.string(),
    default: '',
    serialize: 'raw',
    version: 1,
  }),

  accentCustom: entry({
    id: 'accentCustom',
    key: STORAGE_KEYS.accentCustom,
    schema: z.string(),
    default: '',
    serialize: 'raw',
    version: 1,
  }),

  displayFont: entry({
    id: 'displayFont',
    key: STORAGE_KEYS.displayFont,
    schema: z.string(),
    default: '',
    serialize: 'raw',
    version: 1,
  }),

  locale: entry({
    id: 'locale',
    key: STORAGE_KEYS.locale,
    schema: z.string(),
    default: '',
    serialize: 'raw',
    version: 1,
  }),

  density: entry({
    id: 'density',
    key: STORAGE_KEYS.density,
    schema: z.string(),
    default: '',
    serialize: 'raw',
    version: 1,
  }),

  notificationsEnabled: entry({
    id: 'notificationsEnabled',
    key: STORAGE_KEYS.notificationsEnabled,
    // Stored as the literal string "true"/"false" by notifications.ts.
    schema: z.string(),
    default: '',
    serialize: 'raw',
    version: 1,
  }),

  adminMode: entry({
    id: 'adminMode',
    key: STORAGE_KEYS.adminMode,
    schema: z.string(),
    default: '',
    serialize: 'raw',
    version: 1,
  }),

  // --- One-shot / migration flags (raw "true"/"false" strings) ---
  // These are excluded from backups (see NON_BACKUP_IDS): they are machine-local
  // UI/migration state that should not travel between machines.
  profilesMigrated: entry({
    id: 'profilesMigrated',
    key: STORAGE_KEYS.profilesMigrated,
    schema: z.string(),
    default: '',
    serialize: 'raw',
    version: 1,
  }),

  onboardingDone: entry({
    id: 'onboardingDone',
    key: STORAGE_KEYS.onboardingDone,
    schema: z.string(),
    default: '',
    serialize: 'raw',
    version: 1,
  }),

  showOnboarding: entry({
    id: 'showOnboarding',
    key: STORAGE_KEYS.showOnboarding,
    schema: z.string(),
    default: '',
    serialize: 'raw',
    version: 1,
  }),

  // --- Directory memory ---
  lastDir: entry({
    id: 'lastDir',
    key: STORAGE_KEYS.lastDir,
    schema: z.record(z.string(), z.string()),
    default: {} as Record<string, string>,
    version: 1,
  }),

  recentDirs: entry({
    id: 'recentDirs',
    key: STORAGE_KEYS.recentDirs,
    schema: z.record(z.string(), z.array(z.string())),
    default: {} as Record<string, string[]>,
    version: 1,
  }),
} as const satisfies Record<StorageKeyId | string, RegistryEntry>;

export type RegistryId = keyof typeof REGISTRY;

/**
 * Keys that participate in config backups (export/import). Excludes secrets and
 * one-shot/transient flags that should not travel between machines.
 *
 * Intentionally NOT in the registry (and therefore never in a backup):
 *   - per-provider transient state: "ai-launcher:provider-test:<id>"
 *   - caches: "ai-launcher:updates-cache", ":clis-cache", ":tools-cache"
 *   - dynamic dirs: "ai-launcher:pinned-dirs:<cliKey>"
 *   - "*-changed" storage-event signals (customClis/customIdes/clisOverrides)
 *   - secrets: "ai-launcher-secret:*" (owned by lib/secrets.ts + providers/storage.ts)
 *   - legacy "ai-launcher:session-templates" (read-only during migration)
 */
const NON_BACKUP_IDS: ReadonlySet<RegistryId> = new Set<RegistryId>([
  'profilesMigrated', // one-shot migration flag — machine-local
  'onboardingDone', // first-run UI flag — machine-local
  'showOnboarding', // first-run UI flag — machine-local
]);

export function backupEntries(): RegistryEntry[] {
  return Object.values(REGISTRY).filter(
    (e) => !e.secret && !NON_BACKUP_IDS.has(e.id as RegistryId),
  ) as RegistryEntry[];
}

export function entryById(id: RegistryId): RegistryEntry {
  return REGISTRY[id] as RegistryEntry;
}
