use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct CliInfo {
    pub key: String,
    pub name: String,
    pub command: String,
    pub flag: Option<String>,
    pub install_cmd: String,
    pub version_cmd: String,
    pub npm_pkg: Option<String>,
    pub pip_pkg: Option<String>,
    pub install_method: String,
    pub install_url: Option<String>,
    #[serde(default)]
    pub extra_paths: Vec<String>,
    #[serde(default)]
    pub update_manifest_url: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ToolInfo {
    pub key: String,
    pub name: String,
    pub command: String,
    pub version_cmd: String,
    pub install_hint: String,
    pub install_url: Option<String>,
}

pub fn get_cli_definitions() -> Vec<CliInfo> {
    vec![
        CliInfo {
            key: "claude".into(),
            name: "Claude".into(),
            command: "claude".into(),
            flag: Some("--dangerously-skip-permissions".into()),
            install_cmd: "irm https://claude.ai/install.ps1 | iex".into(),
            version_cmd: "claude --version".into(),
            npm_pkg: Some("@anthropic-ai/claude-code".into()),
            pip_pkg: None,
            install_method: "script".into(),
            install_url: Some(
                "https://docs.anthropic.com/en/docs/agents-and-tools/claude-code/overview".into(),
            ),
            extra_paths: vec![
                r"%USERPROFILE%\.local\bin\claude.exe".into(),
                r"%LOCALAPPDATA%\Programs\claude\bin\claude.exe".into(),
            ],
            update_manifest_url: None,
        },
        CliInfo {
            key: "codex".into(),
            name: "Codex".into(),
            command: "codex".into(),
            flag: Some("--dangerously-bypass-approvals-and-sandbox".into()),
            install_cmd: "npm install -g @openai/codex".into(),
            version_cmd: "codex --version".into(),
            npm_pkg: Some("@openai/codex".into()),
            pip_pkg: None,
            install_method: "npm".into(),
            install_url: None,
            extra_paths: vec![],
            update_manifest_url: None,
        },
        CliInfo {
            key: "antigravity".into(),
            name: "Antigravity".into(),
            command: "agy".into(),
            flag: Some("--dangerously-skip-permissions".into()),
            install_cmd: "iwr https://antigravity.google/cli/install.ps1 -useb | iex".into(),
            version_cmd: "agy --version".into(),
            npm_pkg: None,
            pip_pkg: None,
            install_method: "script".into(),
            install_url: Some("https://antigravity.google/download".into()),
            extra_paths: vec!["%LOCALAPPDATA%\\agy\\bin\\agy.exe".into()],
            update_manifest_url: Some(
                "https://antigravity-cli-auto-updater-974169037036.us-central1.run.app/manifests/windows_amd64.json".into(),
            ),
        },
        CliInfo {
            key: "aider".into(),
            name: "Aider".into(),
            command: "aider".into(),
            flag: Some("--yes-always".into()),
            install_cmd: "pip install -U aider-chat".into(),
            version_cmd: "aider --version".into(),
            npm_pkg: None,
            pip_pkg: Some("aider-chat".into()),
            install_method: "pip".into(),
            install_url: Some("https://aider.chat/docs/install.html".into()),
            extra_paths: vec![r"%USERPROFILE%\.local\bin\aider.exe".into()],
            update_manifest_url: None,
        },
        CliInfo {
            key: "goose".into(),
            name: "Goose".into(),
            command: "goose".into(),
            flag: None,
            install_cmd:
                "$env:CONFIGURE='false'; irm https://github.com/block/goose/raw/main/download_cli.ps1 | iex"
                    .into(),
            version_cmd: "goose --version".into(),
            npm_pkg: None,
            pip_pkg: None,
            install_method: "script".into(),
            install_url: Some("https://block.github.io/goose/".into()),
            extra_paths: vec![r"%USERPROFILE%\.local\bin\goose.exe".into()],
            update_manifest_url: None,
        },
        CliInfo {
            key: "cline".into(),
            name: "Cline CLI".into(),
            command: "cline".into(),
            flag: Some("-y".into()),
            install_cmd: "npm install -g cline".into(),
            version_cmd: "cline --version".into(),
            npm_pkg: Some("cline".into()),
            pip_pkg: None,
            install_method: "npm".into(),
            install_url: Some("https://github.com/cline/cline".into()),
            extra_paths: vec![],
            update_manifest_url: None,
        },
        CliInfo {
            key: "roocode".into(),
            name: "Roo Code".into(),
            command: "roocode".into(),
            flag: Some("-y".into()),
            install_cmd: "npm install -g roocode".into(),
            version_cmd: "roocode --version".into(),
            npm_pkg: Some("roocode".into()),
            pip_pkg: None,
            install_method: "npm".into(),
            install_url: Some("https://roocode.com/".into()),
            extra_paths: vec![],
            update_manifest_url: None,
        },
        CliInfo {
            key: "qwen".into(),
            name: "Qwen".into(),
            command: "qwen".into(),
            flag: Some("--yolo".into()),
            install_cmd: "npm install -g @qwen-code/qwen-code".into(),
            version_cmd: "qwen --version".into(),
            npm_pkg: Some("@qwen-code/qwen-code".into()),
            pip_pkg: None,
            install_method: "npm".into(),
            install_url: None,
            extra_paths: vec![],
            update_manifest_url: None,
        },
        CliInfo {
            key: "kilocode".into(),
            name: "Kilo Code".into(),
            command: "kilo".into(),
            flag: Some("--auto".into()),
            install_cmd: "npm install -g @kilocode/cli".into(),
            version_cmd: "kilo --version".into(),
            npm_pkg: Some("@kilocode/cli".into()),
            pip_pkg: None,
            install_method: "npm".into(),
            install_url: None,
            extra_paths: vec![],
            update_manifest_url: None,
        },
        CliInfo {
            key: "opencode".into(),
            name: "OpenCode".into(),
            command: "opencode".into(),
            flag: Some("--dangerously-skip-permissions".into()),
            install_cmd: "npm install -g opencode-ai".into(),
            version_cmd: "opencode --version".into(),
            npm_pkg: Some("opencode-ai".into()),
            pip_pkg: None,
            install_method: "npm".into(),
            install_url: None,
            extra_paths: vec![],
            update_manifest_url: None,
        },
        CliInfo {
            key: "crush".into(),
            name: "Crush".into(),
            command: "crush".into(),
            flag: Some("--yolo".into()),
            install_cmd: "npm install -g @charmland/crush".into(),
            version_cmd: "crush --version".into(),
            npm_pkg: Some("@charmland/crush".into()),
            pip_pkg: None,
            install_method: "npm".into(),
            install_url: None,
            extra_paths: vec![],
            update_manifest_url: None,
        },
        CliInfo {
            key: "droid".into(),
            name: "Factory Droid".into(),
            command: "droid".into(),
            flag: Some("--skip-permissions-unsafe".into()),
            install_cmd: "irm https://app.factory.ai/cli/windows | iex".into(),
            version_cmd: "droid --version".into(),
            npm_pkg: None,
            pip_pkg: None,
            install_method: "script".into(),
            install_url: Some("https://docs.factory.ai/cli/getting-started/quickstart".into()),
            extra_paths: vec![],
            update_manifest_url: None,
        },
        CliInfo {
            key: "continue".into(),
            name: "Continue".into(),
            command: "cn".into(),
            flag: Some("--yolo".into()),
            install_cmd: "npm install -g @continuedev/cli".into(),
            version_cmd: "cn --version".into(),
            npm_pkg: Some("@continuedev/cli".into()),
            pip_pkg: None,
            install_method: "npm".into(),
            install_url: Some("https://docs.continue.dev/cli".into()),
            extra_paths: vec![],
            update_manifest_url: None,
        },
        CliInfo {
            key: "cody".into(),
            name: "Cody (Sourcegraph)".into(),
            command: "cody".into(),
            flag: None,
            install_cmd: "npm install -g @sourcegraph/cody-ai".into(),
            version_cmd: "cody --version".into(),
            npm_pkg: Some("@sourcegraph/cody-ai".into()),
            pip_pkg: None,
            install_method: "npm".into(),
            install_url: Some("https://sourcegraph.com/docs/cody/clients/install-cli".into()),
            extra_paths: vec![],
            update_manifest_url: None,
        },
        CliInfo {
            key: "copilot".into(),
            name: "GitHub Copilot".into(),
            command: "copilot".into(),
            flag: None,
            install_cmd: "npm install -g @github/copilot".into(),
            version_cmd: "copilot --version".into(),
            npm_pkg: Some("@github/copilot".into()),
            pip_pkg: None,
            install_method: "npm".into(),
            install_url: Some("https://github.com/features/copilot/cli".into()),
            extra_paths: vec![],
            update_manifest_url: None,
        },
    ]
}

pub fn get_tool_definitions() -> Vec<ToolInfo> {
    vec![
        ToolInfo {
            key: "vscode".into(),
            name: "VS Code".into(),
            command: "code".into(),
            version_cmd: "code --version".into(),
            install_hint: "Download de https://code.visualstudio.com".into(),
            install_url: Some("https://code.visualstudio.com/Download".into()),
        },
        ToolInfo {
            key: "cursor".into(),
            name: "Cursor".into(),
            command: "cursor".into(),
            version_cmd: "cursor --version".into(),
            install_hint: "Download de https://cursor.sh".into(),
            install_url: Some("https://cursor.sh".into()),
        },
        ToolInfo {
            key: "windsurf".into(),
            name: "Windsurf".into(),
            command: "windsurf".into(),
            version_cmd: "windsurf --version".into(),
            install_hint: "Download de https://codeium.com/windsurf".into(),
            install_url: Some("https://codeium.com/windsurf".into()),
        },
        ToolInfo {
            key: "antigravity".into(),
            name: "Antigravity".into(),
            command: "antigravity".into(),
            version_cmd: "antigravity --version".into(),
            install_hint: "Download de https://antigravity.google".into(),
            install_url: Some("https://antigravity.google".into()),
        },
        ToolInfo {
            key: "ollama".into(),
            name: "Ollama (Local LLM)".into(),
            command: "ollama".into(),
            version_cmd: "ollama --version".into(),
            install_hint: "Download de https://ollama.com/download/windows".into(),
            install_url: Some("https://ollama.com/download/windows".into()),
        },
    ]
}

/// Metadata for a built-in Claude-compatible provider.
#[derive(Debug, Clone)]
pub struct BuiltinProvider {
    /// Stable identifier matching the `id` field in frontend `seeds.ts`.
    pub id: &'static str,
    /// Human-readable display name.
    pub display_name: &'static str,
}

/// Returns the canonical list of built-in Claude-compatible providers.
pub fn get_builtin_providers() -> &'static [BuiltinProvider] {
    &[
        BuiltinProvider {
            id: "anthropic",
            display_name: "Anthropic (oficial)",
        },
        BuiltinProvider {
            id: "zai",
            display_name: "Z.AI (GLM)",
        },
        BuiltinProvider {
            id: "minimax",
            display_name: "MiniMax",
        },
        BuiltinProvider {
            id: "moonshot",
            display_name: "Moonshot (Kimi)",
        },
        BuiltinProvider {
            id: "qwen",
            display_name: "Qwen (DashScope)",
        },
        BuiltinProvider {
            id: "openrouter",
            display_name: "OpenRouter",
        },
    ]
}
